= Creating Your Own Blogging Engine
Elias Alves Moura <eliasmoura.alves@gmail.com>
v1.0, 2018-01-06
:keywords: blog, blogging, engine, noobkotto
:description: My thoughts/log on creating your own blogging engine

I like to try stuff on my own instead of using the already built ones.
I do this more for an exploration/learning experiment them a "everything already made are bad and we need a new one."

I have being interested in blogging for a long time.
I have made some entries on an website for practicing/learning languages called Lang-8 in the intention to see if I would be able to show my intent for other people through my writing.
I think I did manage to do so.

So that blogging engine... This is a work in progress and I am still trying things out.
I want to be able to blog using just a combination of link:http://asciidoc.org[Asciidoc], link:https://www.gnu.org/software/make[make], link:https://www.git-scm.com[git], link:https://www.gnu.org/software/coreutils[coreutils], shell script and maybe some `awk` and/or `sed` if necessary.
To customize the web page layout I changed the asciidoc `html5.conf` and pass it as option to the asciidoc parser `-f html5.conf` with the `-e` option to disable the implicit load of the system configuration.

Before writing specifics details, the structure of the of the project looks like this:

.Project structure example
....
├── asciidoc.conf                             <1>
├── filters
│   └── source
│       └── source-highlight-filter.conf
├── html5.conf                                <1>
├── img
├── javascript                                <2>
│   ├── asciidoc.js
│   ├── asciidoc.ts
│   ├── ASCIIMathML.js
│   ├── LaTeXMathML.js
│   ├── slidy.js
│   └── toc.js
├── lang-en.conf                              <3>
├── lang-pt-BR.conf                           <3>
├── less
│   └── blog.less                             <4>
├── Makefile                                  <5>
├── README
├── src                                       <6>
└── tools                                     <7>
    └── build_archive.sh
....

<1> Asciidoc configuration with some modifications. "html5.conf" have most of the template for the page that is generated by the asciidoc engine.

<2> Asciidoc javascript stuff…

<3> Language defination of the words like "Index", "Abstract" etc.

<4> The blog css, I am using `less` to experiment its functionalities.

<5> Where general automation happens. In case you do not know how `make`/`makefiles` work, link:https://www.gnu.org/software/make[you might want to have a look in the gnu project page].

<6> Where the asciidoc files I write will be.

<7> Tools I create to generate the some pages. They will be explained in the second part of this series.

I use the switch `-e` so that asciidoc do not pull in system/user configurations and I pass in all the "conf" files needed in the command line. I am using the html5 backend and made some modifications to its layout. Some of those details will be explained in the next post. For now, bellow goes the `Makefile` that made for this project.

[source, makefile, numbered]
----
prefix ?= /srv/noobkotto
DESTDIR ?= /#root dir
BUILD_DIR=html
STATIC_DIR=${BUILD_DIR}/static
BLOG=blog

JS=$(STATIC_DIR)/javascript/asciidoc.js
CSS=$(STATIC_DIR)/css/blog.css $(STATIC_DIR)/css/pygments.css
IMAGES=$(STATIC_DIR)/img/carro_projeto_robotica_2008.jpg \
			 $(STATIC_DIR)/img/elias_portrait_20171206_14_44_18.jpg
ASCIIDOC_CONFIG=-f asciidoc.conf -f html5.conf \
								-f filters/source/source-highlight-filter.conf -f lang-en.conf

POSTS = $(shell ./tools/adoc_files.sh $(BUILD_DIR))

all: build_dir $(CSS) $(JS) $(IMAGES) src/index.adoc src/archive.adoc $(POSTS) \
	$(BUILD_DIR)/archive.html $(BUILD_DIR)/index.html

build_dir:
	@mkdir -p $(STATIC_DIR)/css
	@mkdir -p $(STATIC_DIR)/javascript
	@mkdir -p $(STATIC_DIR)/img

src/archive.adoc:
	./tools/build_archive.sh > src/archive.adoc

src/index.adoc:
	./tools/build_index.sh > src/index.adoc

$(BUILD_DIR)/%.html: src/%.adoc
	asciidoc -o - > $@ -e $(ASCIIDOC_CONFIG) -a website=http://www.noobkoto.com/ $^

${STATIC_DIR}/css/%.css: less/%.less
	lessc $^ $@

$(STATIC_DIR)/javascript/%.js: javascript/%.ts
	tsc --outFile $@ $^

$(STATIC_DIR)/img/%.jpg: img/%.jpg
	cp $^ $@

$(STATIC_DIR)/img/%.png: img/%.png
	cp $^ $@

install: all
	install -d $(DESTDIR)$(prefix)/$(BLOG)
	install -d $(DESTDIR)$(prefix)/$(BLOG)/static
	install -d $(DESTDIR)$(prefix)/$(BLOG)/static/css
	install -d $(DESTDIR)$(prefix)/$(BLOG)/static/javascript
	install -d $(DESTDIR)$(prefix)/$(BLOG)/static/img
	install -m 0644 $(BUILD_DIR)/*.html $(DESTDIR)$(prefix)/$(BLOG)/
	install -m 0644 $(STATIC_DIR)/css/*.css $(DESTDIR)$(prefix)/$(BLOG)/static/css
	install -m 0644 $(STATIC_DIR)/javascript/*.js $(DESTDIR)$(prefix)/$(BLOG)/static/javascript
	install -m 0644 $(STATIC_DIR)/img/* $(DESTDIR)$(prefix)/$(BLOG)/static/img

clean:
	-rm -r $(BUILD_DIR)
	-rm src/archive.adoc src/index.adoc

.PHONY: all build_dir
----
