I wanted a method to blog without to bother with keeping the date and, if possible, using just git to create the publish date.
It "works", but it has a major downfall that will be explained later.
The server has a hook to rebuild the blog every time a commit is
pushed to it.
The hook is this piece of 'sh' code.

..git/hooks/post-receive
[source,sh]
----
#!/bin/sh

TMP_DIR=build_blog.XXX
GIT_DIR=/srv/git/noobkotto/blog
BLOG_DIR=/srv/noobkotto/blog/

TMP_DIR=$(mktemp -p "${TMPDIR:-/tmp}/" -d "$TMP_DIR")

git clone "$GIT_DIR" "$TMP_DIR"
cd "$TMP_DIR"

printf "++++++++++++++++++++++++++++++++++\\n%s\\n" "Building blog."
make
make install prefix=srv/noobkotto/
[ $? ] && printf "++++++++++++++++++++++++++++++++++\\n%s\\n" 'Ok.'

cd -
rm -r "$TMP_DIR"
----

When you push your new commits to the server, the git push log  will look like the example bellow.

.Output of pushing to the server
....
-> git push origin master
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 1.59 KiB | 812.00 KiB/s, done.
Total 9 (delta 3), reused 0 (delta 0)
remote: Cloning into '/tmp/build_blog.ZWv'... <1>
remote: done.
remote: ++++++++++++++++++++++++++++++++++
remote: Building blog.
make output
remote: ++++++++++++++++++++++++++++++++++
remote: Ok.
remote: /srv/git/noobkotto/blog
To noobkotto.com:/srv/git/noobkotto/blog
   ea3578a..add8404  master -> master
....

<1> All the lines with "remote" at the beginning are from the hook shown above. 

I do auto-generation of the archive/index pages and the date of publication through git commit.
The way it works at the moment is by using the first commit of a file as the publish date.
This makes things easy in a way, but it also prevent me from properly using git as I can only commit when I am done with the post.
I might be overlooking some details about the use of git, but for now
it may suffice.

The other scripts that make use of git are:

.tools/build_archive.sh
[source,sh]
----
#!/bin/sh --

# Print the archive.adoc to stdout using `git log` + 'coreutils utilits' to list and order the adoc files by date.

printf "= Index\\nbuild_archive.sh\\n:keywords: archive, blog, noobkotto\\n:description: Blog's post archive.\\n\\n"

for f in src/*.adoc; do
  git log --diff-filter=A --follow --format="%at $f" -- "$f" | tail -1;
done | sort | while read -r date_ doc; do
  link=${doc#src/}
  title="$(head -n 1 "$doc")"
  printf "%s link:%s[%s]\\n\\n"  "$(LANG=C date '+%Y-%m-%d' -d @"$date_")" "${link%adoc}html" "${title#= }"
done
----

As I am using asciidoc to generate the pages, I might as well generate the archive and index pages as .adoc files and then use asciidoc to make the rest.

.tools/build_index.sh
[source,sh]
----
#!/bin/sh --

# Print the archive.adoc to stdout using `git log` + 'coreutils utilits' to list and order the adoc files by date.

printf ":keywords: archive, blog, noobkotto\\n:description: Kotto's blog.\\n\\n"

for f in src/*.adoc; do
  git log --diff-filter=A --follow --format="%at $f" -- "$f" | tail -1;
done | sort --reverse | head -n 3 | while read -r date_ doc; do
  link="${doc#src/}"
  link="${link%adoc}html"
  title="$(head -n 1 "$doc")"
  title="${title#= }"
  printf "\\n== link:%s[%s]\\n%s\\n" "$link" "$title" "$(LANG=C date '+%Y-%m-%d' -d @"$date_")"
  awk 'f{print} /^:description:/{f=1}' "$doc"
done
----

I shall try using tags.
